### ISSUE TITLE
Is this file './datasets/CUB_200_2011/images_discovery_all_3' added by youself? I can not find this file in my old bird dataset folder

### ISSUE THREAD

**Issue by zhangmenghuan-mh** [OatmealLiu/FineR#3]
Is this file './datasets/CUB_200_2011/images_discovery_all_3' added by youself? I can not find this file in my old bird dataset folder

**Comment by OatmealLiu** [comment]
Hi! I saw you closed the issue yourself. So I guess you figured out what is the `images_discovery_all_3` folder for. I'd like to further clarify this point so that might help you get started sooner.

All the folder `images_discovery_all_|D|`, where |D| = [1,10] or 'random' is the data split (number of discovery images per class) we randomly sampled from the original dataset as the **Discovery Dataset**. In the main paper, we reported results for |D|=3 and random, while we reported the results for other number of discovery images in the Apendix.

Thanks for interested in our work. Have fun!

Best regards,
Mingxuan
